# # Banana: Map from Samples

#==

This example demonstrates how to use TransportMaps.jl to approximate
a "banana" distribution using polynomial transport maps when only samples
from the target distribution are available.

Unlike the density-based approach, this method learns the transport map
directly from sample data using optimization techniques.

In the map-from-samples setting, the map also enables density estimation.

==#

using TransportMaps
using Distributions
using Optim
using CairoMakie
using LaTeXStrings
set_theme!(transportmap_theme())
using Statistics

#md using Random # hide
#md Random.seed!(123) # hide
#md nothing # hide

# ## Generate target samples
#
# The target density is
#
# ```math
# \pi(x_1, x_2) = \phi(x_1)\,\phi(x_2 - x_1^2),
# ```
#
# so exact samples can be generated by drawing independent standard-normal
# variables ``u_1,u_2`` and setting ``x_1=u_1`` and ``x_2=u_1^2+u_2``.

function generate_banana_samples(number_samples)
    latent_samples = randn(number_samples, 2)
    return hcat(
        latent_samples[:, 1],
        latent_samples[:, 1] .^ 2 .+ latent_samples[:, 2],
    )
end
#md nothing # hide

# We generate the ``N = 1000`` samples and standardize the samples with the [`LinearMap`](@ref):
target_samples = generate_banana_samples(1_000)
linear_map = LinearMap(target_samples)

# ## Standard-normal reference
#
# Sample-based construction fits a forward map ``S: \boldsymbol{X} \mapsto \boldsymbol{Z}``
# Hence, [`evaluate`](@ref) maps target samples to the reference, while [`inverse`](@ref)
# generates target samples from the reference. The linear map standardizes the data before
# the polynomial map is fitted.

normal_map = PolynomialMap(2, 2, Normal(), Softplus())
normal_result = optimize!(normal_map, target_samples, linear_map)
normal_composed_map = ComposedMap(linear_map, normal_map)

# To check the accuracy of the map, we generate new samples from our target, map them to the
# reference through our map and check mean and standard-deviation:
validation_samples = generate_banana_samples(1_000)
normal_validation_samples = evaluate(normal_composed_map, validation_samples)

println(
    "Mapped normal-reference mean: ",
    vec(mean(normal_validation_samples; dims = 1)),
)
println(
    "Mapped normal-reference std:  ",
    vec(std(normal_validation_samples; dims = 1)),
)

# ## Uniform reference
#
# For the bounded reference we use a shifted Legendre basis. The constrained
# optimizer keeps the fitted training images close to the support of
# `Uniform(0, 1)`.

uniform_distribution = Uniform(0, 1)
uniform_map = PolynomialMap(
    2,
    5,
    uniform_distribution,
    Softplus(),
    ShiftedLegendreBasis(),
)
uniform_result = optimize!(
    uniform_map,
    target_samples,
    linear_map;
    options = Optim.Options(iterations = 120, x_abstol = 1.0e-7),
)
uniform_composed_map = ComposedMap(linear_map, uniform_map)

# Again, we map our validation samples to the reference space and compare the moments:
uniform_validation_samples = evaluate(uniform_composed_map, validation_samples)

println(
    "Mapped uniform-reference mean: ",
    vec(mean(uniform_validation_samples; dims = 1)),
)
println(
    "Mapped uniform-reference std:  ",
    vec(std(uniform_validation_samples; dims = 1)),
)

# ## Target/reference comparison

#==
Since we constructed the map ``S`` from samples, the left panel shows the samples
after `evaluate` maps them into reference space. The right panel shows the
validation samples in ``\boldsymbol{X}`` over the fitted [`pullback`](@ref) density

```math
\pi(\boldsymbol{x}) \approx \rho(S(\boldsymbol{x})) | \det \nabla S(\boldsymbol{x}) |
```

==#

x₁ = range(-4, 4, length = 120)
x₂ = range(-3.5, 7, length = 120)

normal_comparison = reference_target_plot(
    normal_composed_map, validation_samples;
    xgrid = x₁, ygrid = x₂,
    reference_axis = (; limits = ((-4, 4), (-4, 4))),
    figure = (; size = (600, 400)),
)
#md save("banana-samples-normal-reference.svg", normal_comparison); nothing # hide
# ![Sample-based banana map to a standard-normal reference](banana-samples-normal-reference.svg)

uniform_comparison = reference_target_plot(
    uniform_composed_map, validation_samples;
    xgrid = x₁, ygrid = x₂,
    reference_axis = (; limits = ((0, 1), (0, 1))),
    figure = (; size = (600, 400)),
)
#md save("banana-samples-uniform-reference.svg", uniform_comparison); nothing # hide
# ![Sample-based banana map to a uniform reference](banana-samples-uniform-reference.svg)

# The reference-space panels make the effect of changing the reference density
# explicit, while the target-space panels keep the fitted data and true banana
# geometry visible beside them.
